### ISSUE TITLE
Ask for documentation

### ISSUE THREAD

**Issue by realtebo** [vemcogroup/laravel-sparkpost-driver#1]
Hi ! 
Please, could you document the meaning and allowed values of the various options for sparkpost?

```
'sparkpost' => [
    'secret' => env('SPARKPOST_SECRET'),
    'guzzle' => [
        'verify' => true,
        'decode_content' => true,
    ],
    'options' => [
        'open_tracking' => false,
        'click_tracking' => false,
        'transactional' => true,
    ],
],
```

Also: is the 5.8 'endpoint' option supported?

```
'options' =>  [
            'endpoint' => env('SPARKPOST_ENDPOINT'),
        ]
```

this is a MUST because sparkpost uses now app.eu.sparkpost.com domain instead of app.sparkpost.com for Europe GDR-compliance.

**Comment by eldor** [comment]
Thank you for the comments.
I have updated the README with documentation for options and the endpoint.
Its release as 1.1.1

**Comment by eldor** [comment]
Changed it to version 2.0.0 as the endpoint option could be breaking changes

**Comment by realtebo** [comment]
Thank yout a lot
