### ISSUE TITLE
update to latest guzzle

### ISSUE THREAD

**Issue by simonj** [vemcogroup/laravel-sparkpost-driver#13]
Thanks for a really nice package!

is it me or can't we use the latest guzzle version ? https://github.com/guzzle/guzzle/releases

**Comment by eldor** [comment]
Hi,

Thanks for kind words.
Yes you should be able to install latest Guzzle with this package.

It's set for ^7.0.1 which mean any updates in 7.x.x range is acceptable.
Are you sure you dont have another package installed that blocks the Guzzle version?

Remember to use version 8 for L8 and Guzzle 7 support.
