### ISSUE TITLE
Replacement for clarification/sparkpost-laravel-driver

### ISSUE THREAD

**Issue by Lidbetter** [vemcogroup/laravel-sparkpost-driver#15]
Hello,

I no longer have as much time as I would like to maintain:
https://github.com/clarification/sparkpost-laravel-driver

I plan to mark it as abandoned on packagist, would you have any objections to me making https://github.com/vemcogroup/laravel-sparkpost-driver the suggested replacement?

**Comment by eldor** [comment]
Hi @Lidbetter our package is actually build based in yours so of course it's ok to suggest the replacement.
We are using this package for our own software, so it will be maintained.

Have a good day.
