### ISSUE TITLE
Is this package going to support Laravel 9?

### ISSUE THREAD

**Issue by LukeTowers** [vemcogroup/laravel-sparkpost-driver#16]
Laravel 9 moved to Symfony Mailer instead of SwiftMailer (see https://github.com/laravel/framework/pull/38481), will this package be updated to target Symfony Mailer for Laravel 9?

**Comment by eldor** [comment]
Hi @LukeTowers,

Thank you for your question, and yes, we are aware that Laravel 9 will change over to Symfony Mailer, and will have an update ready at Laravel 9 release.

**Comment by eldor** [comment]
Hi @LukeTowers 

You can now test the 5.0.0 release which are prepared for Laravel 9
