### ISSUE TITLE
Composer require Laravel version ^9 and php 8

### ISSUE THREAD

**Issue by divanski** [vemcogroup/laravel-sparkpost-driver#20]
After `composer require vemcogroup/laravel-sparkpost-driver`

Problem 1
    - vemcogroup/laravel-sparkpost-driver 5.0.0 requires laravel/framework ^9.0 -> found laravel/framework[v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^8.40).
    - vemcogroup/laravel-sparkpost-driver[5.0.1, ..., 5.0.3] require php ^8.0.2 -> your php version (7.3.13) does not satisfy that requirement.
    - Root composer.json requires vemcogroup/laravel-sparkpost-driver ^5.0 -> satisfiable by vemcogroup/laravel-sparkpost-driver[5.0.0, 5.0.1, 5.0.2, 5.0.3].

**Comment by eldor** [comment]
Hi @divanski 
It looks like you are trying to install version 5 on a Laravel 8?
Please use version 4 for Laravel 8.

**Comment by divanski** [comment]
@eldor Yes :) I see now. Thanks for the reply!
