### ISSUE TITLE
Send mail to CC with 5.x version

### ISSUE THREAD

**Issue by thomas-serverhouse** [vemcogroup/laravel-sparkpost-driver#23]
Laravel version: 9.17.0
Package version: 5.0.3

Hi,
I'm trying to send an email with one main recipient and one copy. 
However both receive the email as "to" and the other recipient doesn't appear in the email body.

I tried the same thing on Laravel 8 (8.83.16) and the 4.0.4 version and everything works fine.

For now i can just use SMTP authentication but can you guys take a look?

Thanks

**Comment by eldor** [comment]
Hi @thomas-serverhouse 
Could you sent us an example on how you sent the mail with both 5.0.3 and 4.0.4 then we can replicate it and see if its an easy change.

**Comment by thomas-serverhouse** [comment]
Hi,

Sorry for the late response, i didn't get any notifications when you replied.

I just tried again with a fresh install of L8 and L9.

Here's how i send the email (same problem if i use a mail class)

```php

use Illuminate\Mail\Message;
use Illuminate\Support\Facades\Mail;

// .....

Mail::send('mail', [], function (Message $message) {
    $message->to('mailto@gmail.com');
    $message->cc('mailcc@gmail.com');
    $message->bcc('mailbcc@gmail.com');
    $message->subject('Test Message');
});

```

With Laravel 9 everyone receive the email as "to". 
The header shows for the three of them `To: <xxx@gmail.com>` (with xxx being their own address).

With Laravel 8 everything works as intended.
The header is the same for everyone : `To: mailto@gmail.com Cc: mailcc@gmail.com`

**Comment by makije** [comment]
@thomas-serverhouse could you test PR #28

**Comment by eldor** [comment]
@thomas-serverhouse closing this issue, there has been a PR #28 to test since 6 dec 22.
You are welcome to create a new issue if its still a problem
