### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by MeesterDev** [vemcogroup/laravel-sparkpost-driver#29]
Laravel 10 is currently not supported, we'd like to upgrade :)

I'm not really familiar enough with the inner workins of Laravel or this driver to make a PR, otherwise I'd gladly have done so.

**Comment by eldor** [comment]
Hi @MeesterDev ,

You can update your composer now with version 5.0.5

**Comment by MeesterDev** [comment]
@eldor Great! Thanks for the quick fix/response!
