### ISSUE TITLE
not working on Laravel 7

### ISSUE THREAD

**Issue by g0shed** [vemcogroup/laravel-sparkpost-driver#3]
If I try sending an email 

`Mail::to('mail@example.com')->send(new \App\Mail\UserRegistered())`

with Tinker just hangs and doesnt do anything else

**Comment by eldor** [comment]
Hi @g0shed have you tried the new L7 setup described in the Readme?

**Comment by g0shed** [comment]
@eldor yes I did, no luck

**Comment by g0shed** [comment]
new pull requests #5 & #4

**Comment by eldor** [comment]
Thanks for the PR @g0shed, you beat me to it 👍 Tagged version 3.0.1
