### ISSUE TITLE
If we have multiple recipients, email going separately for each email ids 

### ISSUE THREAD

**Issue by balakrishnan178** [vemcogroup/laravel-sparkpost-driver#32]
Hai Team,

Consider, If sending an email to 4 users means, all 4 people receiving different mail

<img width="694" alt="image" src="https://github.com/vemcogroup/laravel-sparkpost-driver/assets/13781758/c4ec1a3f-30fa-4378-8b2a-273f187dd4a1">

In the old version, we are getting single email with multiple recipients

<img width="677" alt="image" src="https://github.com/vemcogroup/laravel-sparkpost-driver/assets/13781758/9260e310-2e6b-428f-80ad-5ed01ef3acbd">

**We found the reason,** 

In vendor\vemcogroup\laravel-sparkpost-driver\src\Transport\SparkPostTransport.php file, we changed like below

After that, we are getting mail like existing one.

https://prnt.sc/rcVrdX-nVqrp

Issue happening, because of the below update
https://github.com/vemcogroup/laravel-sparkpost-driver/compare/4.0.4...5.0.0
https://prnt.sc/effLbN2XOQ8W

Kindly share how to solve this issue? Do we need to pass any parameters?

**Comment by danijelk** [comment]
try with 5.0.6 to see if same issue exists

**Comment by balakrishnan178** [comment]
ok sir thank you. we will check and confirm
