### ISSUE TITLE
Adding Metadata to Transmissions?

### ISSUE THREAD

**Issue by danhanly** [vemcogroup/laravel-sparkpost-driver#33]
Hi,

I can't find a way for me to add metadata to the transmissions using this driver.

Is this supported?

The sparkpost API supports adding metadata, but I can't find a way for it to work through the driver: https://developers.sparkpost.com/api/transmissions/#transmissions-create-a-transmission

Thanks for your help.

**Comment by danijelk** [comment]
As I see it you should be able to use the $options param, either in constructor or with the setOptions() method.

which is used at the end in a merge
    'json' => array_merge([
                'recipients' => $recipients,
                'content' => $content,
            ], $this->options),
        ]);
