### ISSUE TITLE
feature/to-cc-headers laravel 10 support

### ISSUE THREAD

**Issue by DhanaSekarTechno** [vemcogroup/laravel-sparkpost-driver#35]
Hi Team

I am using the feature/to-cc-headers in my project. 

PHP : 8.1 and Laravel 9
Can you please add support for Laravel 10.x for this to-cc-headers feature.

Thanks

**Comment by danijelk** [comment]
Not sure I follow, we already support L10? What is to-cc-headers?

**Comment by DhanaSekarTechno** [comment]
Hi @danijelk 

Thanks for your reply.

When i am using vemcogroup/laravel-sparkpost-driver : 5.0.5, if i send mail to multiple email ids then it send the mail to all emails separately. So that time if any one person reply to that email means its not send to all the other emails ids. So we are using feature/to-cc-headers branch code to achive this feature. 

![image](https://github.com/vemcogroup/laravel-sparkpost-driver/assets/118272807/b54a957f-b850-4ed6-905c-cb64dba010ff)

Currently my composer.json like this
![image](https://github.com/vemcogroup/laravel-sparkpost-driver/assets/118272807/543d5ba4-322c-4947-9763-0b4257cabd1d)

But when i am try to upgrade laravel 10 means i got this below error
![image](https://github.com/vemcogroup/laravel-sparkpost-driver/assets/118272807/b9787354-4e63-46df-87ad-5143225041b6)

Please share your suggestion.

Thanks

**Comment by danijelk** [comment]
ok, you can switch to normal ^5.0 instead of the branch name, merged it into 5.0.6

**Comment by DhanaSekarTechno** [comment]
Hi @danijelk 

Thanks for your support. I will change and check it. If any issues i will get back to you.
