### ISSUE TITLE
Version constraint for symfony/mailer

### ISSUE THREAD

**Issue by ejunker** [vemcogroup/laravel-sparkpost-driver#39]
I see that from version `5.0.6` to `5.0.7` the version constraint was changed from `symfony/mailer ^6.0` to `^7.0`. The problem is that Laravel 10 still requires `symfony/mailer ^6.0`. You might need to change it to `^6.0 | ^7.0` so that it works with Laravel 10 and 11.

**Comment by danijelk** [comment]
Pushed, thanks!
