### ISSUE TITLE
Similar package

### ISSUE THREAD

**Issue by robsontenorio** [vemcogroup/laravel-sparkpost-driver#9]
Hi,

What different between this packages? It seems does exactly same thing and with same configurations options.

https://github.com/clarification/sparkpost-laravel-driver

**Comment by eldor** [comment]
Hi @robsontenorio 

I dont know if there is any difference at the moment, but when Sparkpost was removed from Laravel the clarification package wasn't updated so we build this inspired by the Clarification package and updated it to handle Laravel 6.x and when Laravel 7.x was released we updated to handle their new Mail Handler.


But feel free to use either one of the packages, they do the same :D
